In [1]:
import pandas as pd
data = pd.Series([20,40,60,80,100])
print(data)

0     20
1     40
2     60
3     80
4    100
dtype: int64

In [3]:
data = pd.Series([10,20,30],index=["x","y","z"])
print(data)

x    10
y    20
z    30
dtype: int64

In [7]:
data = {
    "name": ["ram","vani"],
    "age": [20,25]
}
df = pd.DataFrame(data)
print(df)
print("\n")
print(df.loc[0])

   name  age
0   ram   20
1  vani   25


name    ram
age      20
Name: 0, dtype: object

In [8]:
df=pd.read_csv("C:\\Users\\RVUW229\\Desktop\\ash ketchum - Sheet1.csv")
print(df)

  name class  mark
0  abc  bcom    98
1  def   bba    97
2  ghi   bca    99

In [9]:
df.isnull()

    name  class   mark
0  False  False  False
1  False  False  False
2  False  False  False

In [10]:
df.dropna

<bound method DataFrame.dropna of   name class  mark
0  abc  bcom    98
1  def   bba    97
2  ghi   bca    99>

In [11]:
df.fillna(0)

  name class  mark
0  abc  bcom    98
1  def   bba    97
2  ghi   bca    99

In [15]:
print(df["mark"].mean())
print(df.mark.sum())
print(df.mark.min())
print(df.mark.max())
print(df.mark.count())

98.0
294
97
99
3

In [17]:
import pandas as pd

data = {
    "ID": [1, 2, 3, 4],
    "Name": ["narahc ias", "javrup", "ayruohs", "aggin"],
    "Marks": [67, 911, 69, 119]
}

df = pd.DataFrame(data)

df.to_csv("students.csv",index=False)

print("CSV file created successfully")

CSV file created successfully